replicaCount: 1

image:
  repository: "ghcr.io/jaclopher/frontend-app"
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 80

nginxConfigMapName: "nginx-config"  
pvcName: "shared-pvc"  


namespace: "services"
app:
  name: "frontend" 
service:
  name: "frontend"
  type: "ClusterIP"  
  port: 8080  
  targetPort: http-react 

