replicaCount: 1

image:
  repository: https://github.com/JacLopHer/k8s-project-jlh/tree/main/backend
  tag: latest
  pullPolicy: IfNotPresent

namespace: services

service:
  type: ClusterIP
  port: 8080
