replicaCount: 1

image:
  repository: ghcr.io/jaclopher/backend-app
  tag: latest
  pullPolicy: IfNotPresent

namespace: services

app:
  name: "spring" 

containerPort: 8181

service:
  name: "spring"
  type: "ClusterIP"
  port: 80 
  targetPort: http-spring  
