replicaCount: 1

namespace: databases

image:
  repository: "redis"
  tag: "latest"

service:
  name: "redis"
  type: "ClusterIP"
  port: 6379

app:
  name: "redis"  


persistence:
  enabled: true
  size: 8Gi
  storageClass: "standard"
auth:
  enabled: false

configmap:
  enabled: true
  name: redis-config 