apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
    - port: {{ .Values.service.port }}
      targetPort: backend-port
  selector:
    app: backend
